package vistas;

import com.mysql.cj.xdevapi.Table;
import controlador.*;
import java.util.ArrayList;
import java.util.*;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import models.Funcionario;
import java.time.*;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Home extends javax.swing.JFrame {
    
    FuncionarioControler controlerF = new FuncionarioControler();
    TipoDocumentoControler listaTiposId = new TipoDocumentoControler();
    EstadoCivilControler listaEstadosCiviles = new EstadoCivilControler();
    
    void ListarTipoId(){
        try {            
            JCBtipoid.setModel(listaTiposId.llenarCombo());
        } catch (Exception e) {
            System.out.println("hola, hubo error al llenar el combo box de tipos id");
        }
    }
    
    void ListarEstadoCivil(){
        try {       
            JCBestadocivil.setModel(listaEstadosCiviles.llenarComboEstados());
        } catch (Exception e) {
            System.out.println("hola, hubo error al llenar el combo box de estados civiles");
        } 
    }
    
    void ListarFuncionarios(){
        DefaultTableModel modeloListo = controlerF.listarFuncionarios();
        JTlistafuncionarios.setModel(modeloListo);
    }
    
    public Home() {
        initComponents();
        ListarTipoId();
        ListarEstadoCivil();
        ListarFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBeliminar = new javax.swing.JButton();
        JCBtipoid = new javax.swing.JComboBox<>();
        JTcampoid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JBactualizar = new javax.swing.JButton();
        JDCfechanacimiento = new com.toedter.calendar.JDateChooser();
        JLnombres1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFtelefono = new javax.swing.JTextField();
        JTFdireccion = new javax.swing.JTextField();
        JLnombres2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JCBsexo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JCBestadocivil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTFnumid = new javax.swing.JTextField();
        JLnombres = new javax.swing.JLabel();
        JTFnombres = new javax.swing.JTextField();
        JTFapellidos = new javax.swing.JTextField();
        JBguardar = new javax.swing.JButton();
        JBeditar = new javax.swing.JButton();
        JBrecargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTlistafuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBeliminar.setText("ELIMINAR");
        JBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeliminarActionPerformed(evt);
            }
        });

        JCBtipoid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "M", "F" }));
        JCBtipoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBtipoidActionPerformed(evt);
            }
        });

        jLabel8.setText("Introduzca el numero de identificación de la persona que desea editar o eliminar");

        JBactualizar.setText("GUARDAR CAMBIOS");
        JBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBactualizarActionPerformed(evt);
            }
        });

        JLnombres1.setText("Apellidos:");

        jLabel4.setText("Teléfono:");

        JTFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtelefonoActionPerformed(evt);
            }
        });

        JTFdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdireccionActionPerformed(evt);
            }
        });

        JLnombres2.setText("Dirección:");

        jLabel5.setText("Sexo: ");

        JCBsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel6.setText("Fecha Nacimiento:");

        jLabel7.setText("Estado Civil:");

        JCBestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE FUNCIONARIOS");
        jLabel1.setToolTipText("Vista principal");

        jLabel2.setText("Tipo ID: ");

        jLabel3.setText("Número ID: ");

        JTFnumid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFnumidActionPerformed(evt);
            }
        });

        JLnombres.setText("Nombres: ");

        JTFnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFnombresActionPerformed(evt);
            }
        });

        JTFapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFapellidosActionPerformed(evt);
            }
        });

        JBguardar.setText("GUARDAR NUEVO");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBeditar.setText("EDITAR");
        JBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBeditarActionPerformed(evt);
            }
        });

        JBrecargar.setText("RECARGAR LISTA");
        JBrecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBrecargarActionPerformed(evt);
            }
        });

        JTlistafuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "num_id", "nombres", "apellidos", "sexo", "direccion", "telefono", "fecha_nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTlistafuncionarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JTcampoid, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(JBeliminar)
                        .addGap(18, 18, 18)
                        .addComponent(JBeditar))
                    .addComponent(jLabel8))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBrecargar)
                .addGap(281, 281, 281))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTFnumid)
                                .addComponent(JTFtelefono)
                                .addComponent(JCBsexo, 0, 129, Short.MAX_VALUE)
                                .addComponent(JCBestadocivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCBtipoid, javax.swing.GroupLayout.Alignment.TRAILING, 0, 129, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JLnombres)
                                .addComponent(JLnombres1)
                                .addComponent(JLnombres2)
                                .addComponent(jLabel6))
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JDCfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTFapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(JTFnombres)
                                    .addComponent(JTFdireccion))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(JBactualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JBguardar))))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(182, 182, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBrecargar)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTcampoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBeliminar)
                        .addComponent(JBeditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(JLnombres)
                        .addComponent(JTFnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JCBtipoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(JTFnumid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTFapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLnombres1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLnombres2)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(JCBsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JDCfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JCBestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBactualizar)
                            .addComponent(JBguardar)))
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeliminarActionPerformed
        controlerF.eliminarFuncionario(JTcampoid.getText());
        ListarFuncionarios();
    }//GEN-LAST:event_JBeliminarActionPerformed

    private void JCBtipoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBtipoidActionPerformed

    }//GEN-LAST:event_JCBtipoidActionPerformed

    private void JBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBactualizarActionPerformed
        java.util.Date fechap = new Date(JDCfechanacimiento.getCalendar().getTimeInMillis());
        java.sql.Date fechan = new java.sql.Date(fechap.getTime());
        Funcionario funcionario;
        funcionario = new Funcionario(
            JTFnumid.getText(),
            JTFnombres.getText(),
            JTFapellidos.getText(),
            JCBsexo.getItemAt(JCBsexo.getSelectedIndex()),
            JTFdireccion.getText(),
            JTFtelefono.getText(),
            fechan,
            JCBtipoid.getSelectedIndex()+1,
            JCBestadocivil.getSelectedIndex()+1
        );
        controlerF.update(funcionario);
        ListarFuncionarios();
    }//GEN-LAST:event_JBactualizarActionPerformed

    private void JTFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtelefonoActionPerformed

    }//GEN-LAST:event_JTFtelefonoActionPerformed

    private void JTFdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFdireccionActionPerformed

    private void JTFnumidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnumidActionPerformed

    }//GEN-LAST:event_JTFnumidActionPerformed

    private void JTFnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFnombresActionPerformed

    private void JTFapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFapellidosActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        java.util.Date fechap = new Date(JDCfechanacimiento.getCalendar().getTimeInMillis());
        java.sql.Date fechan = new java.sql.Date(fechap.getTime());
        Funcionario funcionario;
        funcionario = new Funcionario(
            JTFnumid.getText(),
            JTFnombres.getText(),
            JTFapellidos.getText(),
            JCBsexo.getItemAt(JCBsexo.getSelectedIndex()),
            JTFdireccion.getText(),
            JTFtelefono.getText(),
            fechan,
            JCBtipoid.getSelectedIndex()+1,
            JCBestadocivil.getSelectedIndex()+1
        );
        controlerF.crearFuncionario(funcionario);

        System.out.println("creado con exito");
        ListarFuncionarios();
    }//GEN-LAST:event_JBguardarActionPerformed

    private void JBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBeditarActionPerformed
        Funcionario funcionario = controlerF.editarFuncionario(JTcampoid.getText());

        JCBtipoid.setSelectedIndex(funcionario.getTipoDocumento()-1);
        JCBestadocivil.setSelectedIndex(funcionario.getEstadoCivil()-1);
        JTFnumid.setText(funcionario.getNumId());
        JTFnombres.setText(funcionario.getNombres());
        JTFapellidos.setText(funcionario.getApellidos());
        JCBsexo.setSelectedItem(funcionario.getSexo());
        JTFdireccion.setText(funcionario.getDireccion());
        JTFtelefono.setText(funcionario.getTelefono());
        JDCfechanacimiento.setDate(funcionario.getFechaNacimiento());
    }//GEN-LAST:event_JBeditarActionPerformed

    private void JBrecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBrecargarActionPerformed
        DefaultTableModel modeloListo = controlerF.listarFuncionarios();
        JTlistafuncionarios.setModel(modeloListo);
    }//GEN-LAST:event_JBrecargarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBactualizar;
    private javax.swing.JButton JBeditar;
    private javax.swing.JButton JBeliminar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBrecargar;
    private javax.swing.JComboBox<String> JCBestadocivil;
    private javax.swing.JComboBox<String> JCBsexo;
    private javax.swing.JComboBox<String> JCBtipoid;
    private com.toedter.calendar.JDateChooser JDCfechanacimiento;
    private javax.swing.JLabel JLnombres;
    private javax.swing.JLabel JLnombres1;
    private javax.swing.JLabel JLnombres2;
    private javax.swing.JTextField JTFapellidos;
    private javax.swing.JTextField JTFdireccion;
    private javax.swing.JTextField JTFnombres;
    private javax.swing.JTextField JTFnumid;
    private javax.swing.JTextField JTFtelefono;
    private javax.swing.JTextField JTcampoid;
    private javax.swing.JTable JTlistafuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
